---
title: "HNET analysis"
author: "Philipp Chapkovski"
date: "12/30/2020"
output: html_document
---

```{r set - options, echo = FALSE, cache = FALSE}
options(width = 5000)
options(digits = 5)
options(scipen = 50)
options(dplyr.summarise.inform = F)
knitr::opts_chunk$set(
  echo = FALSE,
  cache = T,
  warning = F,
  results = 'markup',
  message = FALSE
)

```

``` {r libraries}
library('pacman')
p_load('dplyr', 'estimatr', 'tidyverse', 'readxl', 'sjPlot', 'emmeans', 'olsrr', 'writexl', 'gtsummary', 'stargazer', 'magrittr', 'ggplot2', 'scales','lemon','knitr','ggpmisc', 'fastDummies', 'estimatr', 'sjPlot','haven',
       'hrbrthemes','kableExtra', 'skimr','lubridate', 'data.table', 'gganimate','transformr', 'png','gifski','summarytools', 'dm', 'DBI')

```

```{r dbconnect}


con <- dbConnect(odbc::odbc(),
                 driver = "/usr/local/lib/libsqlite3odbc.dylib",
                 database = "/Users/chapkovski/archive/hnet_scraper/db.sqlite3")
dm <- dm_from_src(con)


```

## Number of posts per year

```{r preparing data for posts}
posts<-as_tibble(tbl(con, "hnet_structuredpost") )%>%
  mutate(year=lubridate::year(posting_date),
         month=lubridate::month(posting_date),
         day=lubridate::year(posting_date),
         weekday=lubridate::wday(posting_date),
         )

```

```{r plotting }
posts %>% group_byggplot(aes())
```
Posts per year with moving average for 3 months

## Posts per week per year 

## Seasonality (posts per month)

```{r posts-per-month}

posts %>% mutate(monthdate = as.Date(paste("2020", month, '01', sep = "-")))%>%
group_by(monthdate, year) %>% summarise(n=n()) %>%
  ggplot(aes(x=monthdate, y=n))+
  geom_point(, stat='identity') +
  geom_smooth(method = "loess")+
   scale_x_date(date_breaks = "1 month", date_labels = "%b") 


```
## Dynamics of professorship positions vs other positions

## Black studies/Race studies positions

## Feminism/Women studies positions

## Positions posted by continent and country
